version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false

python:
   install:
     - requirements: requirements.txt
