name: CI

on:
  push:
    branches:
      - 'main'
      - '*.*'
      - '!*backport*'
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      submodules: true
      envs: |
        - linux: py311
        - linux: linkcheck
